spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: A1TravelApplication

security:
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - X-Content-Type-Options
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /
    - /api/login
    - /api/account/**
    - /api/user/**
    - /api/logout
    - /api/register
    - /css/**
    - /js/**
    - /api/event/**
    - /api/trip/**
    - /api/flight/**
    - /api/train/
    - /api/car/
    - /api/destination/**
    - /api/message/**
    - /api/announcement/
    - /api/lodging/**
    - /api/flight/**
    - /api/train/**
    - /api/car/**
  exposed-headers:
    - X-Xsrf-Token
    - X-Auth-Token
    - Expires
